name: Build Moluccus

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Gradle
      run: ./gradlew assembleDebug

    - name: Compress APK
      run: zip -9 -r Moluccus.apk app/build/outputs/apk/debug/app-debug.apk

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: Moluccus.apk
        path: Moluccus.apk
      id: upload_apk

    - name: Set output
      run: echo "::set-output name=artifact_url::$(echo ${GITHUB_SERVER_URL}/${{ github.repository }}/raw/master/${{ steps.upload_apk.outputs.uploaded_filename }})"
      id: set_output

    - name: Output URL
      run: echo ${{ steps.set_output.outputs.artifact_url }}

