name: Build Moluccus

on:
  push:
    branches: [master]
    
env:
  GITHUB_TOKEN: ${{ secrets.MOLUCCUS_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Gradle
      run: ./gradlew assembleDebug

    - name: Extract Version Name
      run: |
        VERSION_NAME=$(./gradlew -q printVersionName)
        aapt2 dump badging app/build/outputs/apk/debug/app-debug.apk | grep versionName | awk '{print $4}' | sed s/versionName=//g | sed s/\'//g > version.txt

    - name: Read Version Name
      id: version
      run: echo "::set-output name=value::$(cat version.txt)"

    - name: Compress APK
      run: zip -9 -r Moluccus.apk app/build/outputs/apk/debug/app-debug.apk

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: Moluccus.apk
        path: Moluccus.apk
      id: upload_apk

    - name: Set output
      run: echo "::set-output name=artifact_url::$(echo ${GITHUB_SERVER_URL}/${{ github.repository }}/raw/master/${{ steps.upload_apk.outputs.uploaded_filename }})"
      id: set_output

    - name: Create Release
      uses: actions/create-release@v1
      with:
        tag_name: v1.0.1
        release_name: Release 
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.MOLUCCUS_TOKEN }}
      id: create_release

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./Moluccus.apk
        asset_name: Moluccus.apk
        asset_content_type: application/vnd.android.package-archive
      env:
        GITHUB_TOKEN: ${{ secrets.MOLUCCUS_TOKEN }}
